version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dronefeeder
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dronefeeder
