version: "3.8"
services:
  application:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dronefeeder
    ports:
      - 3306:3306
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    